dist: trusty
sudo: true
language: ruby
python:
- 2.7
rvm:
  - 2.5
  - 2.4
  - ruby-head
addons:
  apt:
    packages:
    - python-lxml
    - python-pip

before_install:
  - gem install bundler -v 1.16.1
  - unset _JAVA_OPTIONS
  - pip install --user xml2rfc
matrix:
  allow_failures:
    - rvm: ruby-head
